openapi: 3.0.3
info:
  title: 3GPP APIs
  description: HTTP messages and data types sent over 3GPP AS an VS APIs
  contact: {}
  version: '1.0'
servers:
  - url: http://localhost:8080/stir/v1
    description: 3GPP Endpoint
tags:
  - name: signing
    description: AS Endpoint
  - name: verification
    description: VS Endpoint
paths:
  /signing:
    post:
      tags:
        - signing
      summary: AS Request
      operationId: signingPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/shakenSigningRequest'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/signingResponse'
        '400':
          description: Error in processing request 
          content:
            application/json:
              examples:
                missingRequestBody:
                  summary: Missing Request Body
                  value:
                    error: Missing request body
                missingMandatoryParameter:
                  summary: Missing Mandatory Parameter
                  value:
                    error: Missing Mandatory Parameter
                invalidParameterValue:
                  summary: Invalid Parameter Value
                  value:
                    error: Invalid Parameter Value
                failedToParseMessageBody:
                  summary: failedToParseMessageBody
                  value:
                    error: Failed To Parse Message Body
        '406':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Requested response body type is not supported
                    description: The request could not be processed due to a not supported message body format.
        '404':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Requested resource not found
                    description: The request could not be processed due to no resource available related to the Request-URI.
        '415':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Unsupported request body type
                    description: The request could not be processed due to not supported message body.
        '411':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Missing mandatory Content-Length headers
                    description: The request could not be processed due to a missing Content-Length header.
        '405':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Method not allowed
                    description: The resource was invoked with unsupported operation.
        '500':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Internal server error
                    description: The request failed due to internal error.
  /divSigning:
    post:
      tags:
        - signing
      summary: Diversion AS Request
      operationId: divSigningPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/divSigningRequest'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/signingResponse'
        '400':
          description: Error in processing request 
          content:
            application/json:
              examples:
                missingRequestBody:
                  summary: Missing Request Body
                  value:
                    error: Missing request body
                missingMandatoryParameter:
                  summary: Missing Mandatory Parameter
                  value:
                    error: Missing Mandatory Parameter
                invalidParameterValue:
                  summary: Invalid Parameter Value
                  value:
                    error: Invalid Parameter Value
                failedToParseMessageBody:
                  summary: failedToParseMessageBody
                  value:
                    error: Failed To Parse Message Body
        '406':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Requested response body type is not supported
                    description: The request could not be processed due to a not supported message body format.
        '404':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Requested resource not found
                    description: The request could not be processed due to no resource available related to the Request-URI.
        '415':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Unsupported request body type
                    description: The request could not be processed due to not supported message body.
        '411':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Missing mandatory Content-Length headers
                    description: The request could not be processed due to a missing Content-Length header.
        '405':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Method not allowed
                    description: The resource was invoked with unsupported operation.
        '500':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Internal server error
                    description: The request failed due to internal error.
  /rphSigning:
    post:
      tags:
        - signing
      summary: RPH AS Request
      operationId: rphsigningPOST
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rphSigningRequest'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/signingResponse'
        '400':
          description: Error in processing request 
          content:
            application/json:
              examples:
                missingRequestBody:
                  summary: Missing Request Body
                  value:
                    error: Missing request body
                missingMandatoryParameter:
                  summary: Missing Mandatory Parameter
                  value:
                    error: Missing Mandatory Parameter
                invalidParameterValue:
                  summary: Invalid Parameter Value
                  value:
                    error: Invalid Parameter Value
                failedToParseMessageBody:
                  summary: failedToParseMessageBody
                  value:
                    error: Failed To Parse Message Body
        '406':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Requested response body type is not supported
                    description: The request could not be processed due to a not supported message body format.
        '404':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Requested resource not found
                    description: The request could not be processed due to no resource available related to the Request-URI.
        '415':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Unsupported request body type
                    description: The request could not be processed due to not supported message body.
        '411':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Missing mandatory Content-Length headers
                    description: The request could not be processed due to a missing Content-Length header.
        '405':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Method not allowed
                    description: The resource was invoked with unsupported operation.
        '500':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Internal server error
                    description: The request failed due to internal error.
  /verification:
    post:
      tags:
        - verification
      summary: VS Request
      operationId: verificationPost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/shakenVerificationRequest'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/verificationResponse'
        '400':
          description: Error in processing request 
          content:
            application/json:
              examples:
                missingRequestBody:
                  summary: Missing Request Body
                  value:
                    error: Missing request body
                missingMandatoryParameter:
                  summary: Missing Mandatory Parameter
                  value:
                    error: Missing Mandatory Parameter
                invalidParameterValue:
                  summary: Invalid Parameter Value
                  value:
                    error: Invalid Parameter Value
                failedToParseMessageBody:
                  summary: failedToParseMessageBody
                  value:
                    error: Failed To Parse Message Body
        '406':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Requested response body type is not supported
                    description: The request could not be processed due to a not supported message body format.
        '404':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Requested resource not found
                    description: The request could not be processed due to no resource available related to the Request-URI.
        '415':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Unsupported request body type
                    description: The request could not be processed due to not supported message body.
        '411':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Missing mandatory Content-Length headers
                    description: The request could not be processed due to a missing Content-Length header.
        '405':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Method not allowed
                    description: The resource was invoked with unsupported operation.
        '500':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Internal server error
                    description: The request failed due to internal error.
  /divVerification:
    post:
      tags:
        - verification
      summary: Diversion VS Request
      operationId: divVerificationPost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/divVerificationRequest'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/verificationResponse'
        '400':
          description: Error in processing request 
          content:
            application/json:
              examples:
                missingRequestBody:
                  summary: Missing Request Body
                  value:
                    error: Missing request body
                missingMandatoryParameter:
                  summary: Missing Mandatory Parameter
                  value:
                    error: Missing Mandatory Parameter
                invalidParameterValue:
                  summary: Invalid Parameter Value
                  value:
                    error: Invalid Parameter Value
                failedToParseMessageBody:
                  summary: failedToParseMessageBody
                  value:
                    error: Failed To Parse Message Body
        '406':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Requested response body type is not supported
                    description: The request could not be processed due to a not supported message body format.
        '404':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Requested resource not found
                    description: The request could not be processed due to no resource available related to the Request-URI.
        '415':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Unsupported request body type
                    description: The request could not be processed due to not supported message body.
        '411':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Missing mandatory Content-Length headers
                    description: The request could not be processed due to a missing Content-Length header.
        '405':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Method not allowed
                    description: The resource was invoked with unsupported operation.
        '500':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Internal server error
                    description: The request failed due to internal error.
  /rphVerification:
    post:
      tags:
        - verification
      summary: RPH VS Request
      operationId: rphVerificationPost
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rphVerificationRequest'
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/verificationResponse'
        '400':
          description: Error in processing request 
          content:
            application/json:
              examples:
                missingRequestBody:
                  summary: Missing Request Body
                  value:
                    error: Missing request body
                missingMandatoryParameter:
                  summary: Missing Mandatory Parameter
                  value:
                    error: Missing Mandatory Parameter
                invalidParameterValue:
                  summary: Invalid Parameter Value
                  value:
                    error: Invalid Parameter Value
                failedToParseMessageBody:
                  summary: failedToParseMessageBody
                  value:
                    error: Failed To Parse Message Body
        '406':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Requested response body type is not supported
                    description: The request could not be processed due to a not supported message body format.
        '404':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Requested resource not found
                    description: The request could not be processed due to no resource available related to the Request-URI.
        '415':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Unsupported request body type
                    description: The request could not be processed due to not supported message body.
        '411':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Missing mandatory Content-Length headers
                    description: The request could not be processed due to a missing Content-Length header.
        '405':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Method not allowed
                    description: The resource was invoked with unsupported operation.
        '500':
          description: Error in processing request 
          content:
            application/json:
              schema: 
                required: 
                  - error
                type: object
                properties: 
                  error: 
                    type: string
                    example: Internal server error
                    description: The request failed due to internal error.
components:
  schemas:
    shakenSigningRequest:
      title: signingRequest
      type: object
      required: 
        - attest
        - dest
        - iat
        - orig
        - origid
        - rph
        - sph
      properties:
        ppt:
          type: string
          example: shaken, div or rph
          description: Optional field. If it's empty request is considered as "shaken" request. If "div", request is considered as "divSigning" request and if "rph", request is considered as "rphSigning" request
        attest: 
          type: string
          example: A , B or C
          description: Identifying the relation between the service provider attesting the identity and the subscriber
        dest:
          type: array
          items:
            type: string
          description: Identifying the called user taken from the To header field for a shaken or rph PASSporT, and from the Request-URI after retargeting for a div PASSporT
          example: [{"uri":["sip:alice@example.com"]},{"tn":["12155551213"]}]
        div: 
          type: string
          description: Identifying the diverting user; i.e., the user identified in the Request-URI before retargeting, taken from the History-Info header field
          example: {"tn":"121555551213"}
        iat: 
          type: integer
          description: Time since 1 January 1970 in Numeric Date format
          example: 1664199282
        orig: 
          type: string
          description: Identifying the calling user
          example: {"tn":"12155551212"}
        origid: 
          type: string
          description: The value of "origid" claim is a Universally Unique Identifier (UUID)
          example: 123e4567-e89b-12d3-a456-426655440000
        rph: 
          type: array
          items:
            type: string
          description: Array of strings that correspond to the r-values indicated in the SIP Resource-Priority header field. Contains assertion of the priority level of the user to be used for a given communication session
          example: [{"auth":["ets.0", "wps.0"]}]
        sph: 
          type: string
          description: Contains header field value "psap-callback" of the SIP Priority header field
          example: psap-callback
        hi: 
          type: string
          description: The "index" header field parameter is included in the entry identifying the diverting user in the History-Info header field
        tn: 
          type: string
          description: allowed characters as for local-number-digits and global-number-digits defined in RFC 3966 [22]. The number needs to be in canonical form according to RFC 8224 [252]
        uri: 
          type: string
          description: A SIP URI as specified in RFC 3261 [26] following the generic guidelines in RFC. Used if the "orig" or "dest" is given in a SIP URI
    rphSigningRequest:
      title: signingRequest
      type: object
      required: 
        - dest
        - div
        - iat
        - orig
      properties:
        attest: 
          type: string
          example: A , B or C
          description: Identifying the relation between the service provider attesting the identity and the subscriber
        dest:
          type: array
          items:
            type: string
          description: Identifying the called user taken from the To header field for a shaken or rph PASSporT, and from the Request-URI after retargeting for a div PASSporT
          example: [{"uri":["sip:alice@example.com"]},{"tn":["12155551213"]}]
        div: 
          type: string
          description: Identifying the diverting user; i.e., the user identified in the Request-URI before retargeting, taken from the History-Info header field
          example: {"tn":"121555551213"}
        iat: 
          type: integer
          description: Time since 1 January 1970 in Numeric Date format
          example: 1664199282
        orig: 
          type: string
          description: Identifying the calling user
          example: {"tn":"12155551212"}
        origid: 
          type: string
          description: The value of "origid" claim is a Universally Unique Identifier (UUID)
          example: 123e4567-e89b-12d3-a456-426655440000
        rph: 
          type: array
          items:
            type: string
          description: Array of strings that correspond to the r-values indicated in the SIP Resource-Priority header field. Contains assertion of the priority level of the user to be used for a given communication session
          example: [{"auth":["ets.0", "wps.0"]}]
        sph: 
          type: string
          description: Contains header field value "psap-callback" of the SIP Priority header field
          example: psap-callback
        hi: 
          type: string
          description: The "index" header field parameter is included in the entry identifying the diverting user in the History-Info header field
        tn: 
          type: string
          description: allowed characters as for local-number-digits and global-number-digits defined in RFC 3966 [22]. The number needs to be in canonical form according to RFC 8224 [252]
        uri: 
          type: string
          description: A SIP URI as specified in RFC 3261 [26] following the generic guidelines in RFC. Used if the "orig" or "dest" is given in a SIP URI
    divSigningRequest:
      title: signingRequest
      type: object
      required: 
        - dest
        - iat
        - orig
        - rph
      properties:
        attest: 
          type: string
          example: A , B or C
          description: Identifying the relation between the service provider attesting the identity and the subscriber
        dest:
          type: array
          items:
            type: string
          description: Identifying the called user taken from the To header field for a shaken or rph PASSporT, and from the Request-URI after retargeting for a div PASSporT
          example: [{"uri":["sip:alice@example.com"]},{"tn":["12155551213"]}]
        div: 
          type: string
          description: Identifying the diverting user; i.e., the user identified in the Request-URI before retargeting, taken from the History-Info header field
          example: {"tn":"121555551213"}
        iat: 
          type: integer
          description: Time since 1 January 1970 in Numeric Date format
          example: 1664199282
        orig: 
          type: string
          description: Identifying the calling user
          example: {"tn":"12155551212"}
        origid: 
          type: string
          description: The value of "origid" claim is a Universally Unique Identifier (UUID)
          example: 123e4567-e89b-12d3-a456-426655440000
        rph: 
          type: array
          items:
            type: string
          description: Array of strings that correspond to the r-values indicated in the SIP Resource-Priority header field. Contains assertion of the priority level of the user to be used for a given communication session
          example: [{"auth":["ets.0", "wps.0"]}]
        sph: 
          type: string
          description: Contains header field value "psap-callback" of the SIP Priority header field
          example: psap-callback
        hi: 
          type: string
          description: The "index" header field parameter is included in the entry identifying the diverting user in the History-Info header field
        tn: 
          type: string
          description: allowed characters as for local-number-digits and global-number-digits defined in RFC 3966 [22]. The number needs to be in canonical form according to RFC 8224 [252]
        uri: 
          type: string
          description: A SIP URI as specified in RFC 3261 [26] following the generic guidelines in RFC. Used if the "orig" or "dest" is given in a SIP URI
    signingResponse:
      title: signingResponse
      type: object
      required: 
        - identityHeader
      properties:
        identityHeader:
          type: string
          description: Identity header field value as specified in RFC 8224 [252]. This string cannot be NULL
          example: "eyJhbGciOiJFUzI1NiIsInBwdCI6InNoYWtlbiIsInR5cCI6InBhc3Nwb3J0IiwieDV1IjoiaHR0cDovL05FVS1DMDJGRzJLN01MODU6ODA4MC9jY2lkL2F1dGhuL3YyL2NlcnRzLzExMDAxLjEwMDAxIn0.eyJhdHRlc3QiOiJBIiwiZGVzdCI6eyJ0biI6WyIxNTcxNTU1MDAwMCJdfSwiaWF0IjoxNjQ5NTM2NTMxLCJvcmlnIjp7InVyaSI6InNpcDphbGljZUBleGFtcGxlLmNvbSJ9LCJvcmlnaWQiOiJjODcyNDU3NS1iNzgxLTExZWMtYjU3NC0wMjQyYWMxMTAwMDIifQ.piGZhwqwWaKM4cOcrDTMeFKOY5UlekVDlKZTxlge4x0ERnSe9uW4400gaoVFdpGiTOzoCt9QdSfwLV_hcmvT0g;info=<http://NEU-C02FG2K7ML85:8080/ccid/authn/v2/certs/11001.10001>;alg=ES256;ppt=\"shaken\""
    errorResponse400a:
      title: errorResponseMissingRequestBody
      type: object
      required: 
        - error
      properties:
        error:
          type: string
          description: The request could not be processed due to missing request body.          
          example: Missing request body
    errorResponse400b:
      title: errorResponseMissingMandatoryParameter
      type: object
      required: 
        - error
      properties:
        error:
          type: string
          description: The request could not be processed due to missing parameters.
          example: Missing mandatory parameter
    errorResponse400c:
      title: errorResponseInvalidParameterValue
      type: object
      required: 
        - error
      properties:
        error:
          type: string
          description: The request could not be processed due to invalid parameter value.
          example: Invalid parameter value
    errorResponse400d:
      title: errorResponseFailedToParseMessageBody
      type: object
      required: 
        - error
      properties:
        error:
          type: string
          description: The request could not be processed due to failure to parse the message body
          example: Failed to parse message body
    shakenVerificationRequest:
      title: verificationRequest
      type: object
      required: 
        - identityHeader
        - to
        - time
        - from
      properties:
        identityHeader:
          type: string
          description: This parameter contains the "shaken" Identity header field value to be verified
          example: "eyJhbGciOiJFUzI1NiIsInBwdCI6InNoYWtlbiIsInR5cCI6InBhc3Nwb3J0IiwieDV1IjoiaHR0cDovL05FVS1DMDJGRzJLN01MODU6ODA4MC9jY2lkL2F1dGhuL3YyL2NlcnRzLzExMDAxLjEwMDAxIn0.eyJhdHRlc3QiOiJBIiwiZGVzdCI6eyJ0biI6WyIxNTcxNTU1MDAwMCJdfSwiaWF0IjoxNjQ5NTM2NTMxLCJvcmlnIjp7InVyaSI6InNpcDphbGljZUBleGFtcGxlLmNvbSJ9LCJvcmlnaWQiOiJjODcyNDU3NS1iNzgxLTExZWMtYjU3NC0wMjQyYWMxMTAwMDIifQ.piGZhwqwWaKM4cOcrDTMeFKOY5UlekVDlKZTxlge4x0ERnSe9uW4400gaoVFdpGiTOzoCt9QdSfwLV_hcmvT0g;info=<http://NEU-C02FG2K7ML85:8080/ccid/authn/v2/certs/11001.10001>;alg=ES256;ppt=\"shaken\""
        identityHeaders:
          type: array
          items:
            type: string
          description: This array contains the "div" and "rph" Identity header field values to be verified
          example: [eyJhbGciOiJFUzI1NiIsInBwdCI6InNoYWtlbiIsInR5cCI6InBhc3Nwb3J0IiwieDV1IjoiaHR0cDovL05FVS1DMDJGRzJLN01MODU6ODA4MC9jY2lkL2F1dGhuL3YyL2NlcnRzLzExMDAxLjEwMDAxIn0.eyJhdHRlc3QiOiJBIiwiZGVzdCI6eyJ0biI6WyIxNTcxNTU1MDAwMCJdfSwiaWF0IjoxNjQ5NTM2NTMxLCJvcmlnIjp7InVyaSI6InNpcDphbGljZUBleGFtcGxlLmNvbSJ9LCJvcmlnaWQiOiJjODcyNDU3NS1iNzgxLTExZWMtYjU3NC0wMjQyYWMxMTAwMDIifQ.piGZhwqwWaKM4cOcrDTMeFKOY5UlekVDlKZTxlge4x0ERnSe9uW4400gaoVFdpGiTOzoCt9QdSfwLV_hcmvT0g;info=<http://NEU-C02FG2K7ML85:8080/ccid/authn/v2/certs/11001.10001>;alg=ES256;ppt=\"shaken\",eyJhbGciOiJFUzI1NiIsInBwdCI6InNoYWtlbiIsInR5cCI6InBhc3Nwb3J0IiwieDV1IjoiaHR0cDovL05FVS1DMDJGRzJLN01MODU6ODA4MC9jY2lkL2F1dGhuL3YyL2NlcnRzLzExMDAxLjEwMDAxIn0.eyJhdHRlc3QiOiJBIiwiZGVzdCI6eyJ0biI6WyIxNTcxNTU1MDAwMCJdfSwiaWF0IjoxNjQ5NTM2NTMxLCJvcmlnIjp7InVyaSI6InNpcDphbGljZUBleGFtcGxlLmNvbSJ9LCJvcmlnaWQiOiJjODcyNDU3NS1iNzgxLTExZWMtYjU3NC0wMjQyYWMxMTAwMDIifQ.piGZhwqwWaKM4cOcrDTMeFKOY5UlekVDlKZTxlge4x0ERnSe9uW4400gaoVFdpGiTOzoCt9QdSfwLV_hcmvT0g;info=<http://NEU-C02FG2K7ML85:8080/ccid/authn/v2/certs/11001.10001>;alg=ES256;ppt=\"shaken\"]
        to: 
          type: string
          description: The destination identity taken from the To header field. Used when no div claim is included
          example: "sip:alice@example.com or 12155551213"
        dest: 
          type: string
          description: The destination identity taken from the Request-URI in the incoming request
          example: "sip:alice@example.com or 12155551213"
        time: 
          type: integer
          description: Time based on the Date header field in the incoming request
          example: 1664216863
        from: 
          type: string
          description: The asserted identity, taken from the P-Asserted-Identity or the From header field of the incoming request
          example: "sip:alice@example.com or 12155551213"
        protectedHeaders: 
          type: array
          items:
            type: string
          description: Contains the SIP header field(s) protected by claims in the PASSporT(s) of the identityHeaders array
    verificationResponse:
      title: verificationResponse
      type: object
      properties:
        divResult:
          type: array
          items:
            type: string
          description: Parameter informing of the result of the verification of diverting identities. For each verified identity the verstat parameter is added to the verified identity
        verstatValue: 
          type: string
          description: Parameter informing of the result of the verification of originating identity. To be used in the verstat parameter added to the verified identity. The parameter is mandatory if the request contained a PASSporT SHAKEN JSON Web Token
        verstatPriority: 
          type: string
          description: Parameter informing of the result of the verification of the Resource-Priority header field and optionally the header field value "psap-callback" of the Priority header field
        verifyResults:
          description: Each array entry contains the verification results of a PASSporT contained in the request
          type: array
          items:
            type: object
            required: 
              - verifyResult
              - ppt
              - status
            properties:
              verifyResult: 
                description: Contains the verification results of a single Identity header field contained in the identityHeader parameter or an entry of the identityHeaders array of the verification request.The ppt and status parameters are always present. The inclusion of the other parameters in the tuple depends on the value of the status parameter
                type: array
                items:
                  type: object
                  required: 
                    - verifyResult
                    - ppt
                    - status
                  properties:
                    reasonCode: 
                      type: integer
                      description: Identifies the 4xx failure reason code of the failing PASSporT. Optional since they are included only when the verifyResult "status" parameter has a value of "fail"
                    reasonText: 
                      type: string
                      description: Identifies the failure text associated with the 4xx failure reason code. Optional since they are included only when the verifyResult "status" parameter has a value of "fail"
                    passport: 
                      type: string
                      description: Contains the failing PASSporT. Optional since they are included only when the verifyResult "status" parameter has a value of "fail"
                    validClaims: 
                      type: string
                      description: The validClaims parameter contains the payload of the verified PASSporT. Optional since they are included only when the verifyResult "status" parameter has a value of "pass"
              ppt: 
                type: string
                description: Identifies the type of PASSporT associated with this array entry
              status: 
                type: string
                description: Identifies the verification result of the PASSporT associated with this array entry
    divVerificationRequest:
      title: divVerificationRequest
      type: object
      required: 
        - identityHeader
        - identityHeaders
        - to
        - time
        - from
      properties:
        identityHeader:
          type: string
          description: This parameter contains the "shaken" Identity header field value to be verified
        identityHeaders:
          type: array
          items:
            type: string
          description: This array contains the "div" and "rph" Identity header field values to be verified
        to: 
          type: string
          description: The destination identity taken from the To header field. Used when no div claim is included
        dest: 
          type: string
          description: The destination identity taken from the Request-URI in the incoming request
        time: 
          type: integer
          description: Time based on the Date header field in the incoming request
        from: 
          type: string
          description: The asserted identity, taken from the P-Asserted-Identity or the From header field of the incoming request
        protectedHeaders: 
          type: array
          items:
            type: string
          description: Contains the SIP header field(s) protected by claims in the PASSporT(s) of the identityHeaders array
    rphVerificationRequest:
      title: rphVerificationRequest
      type: object
      required: 
        - identityHeader
        - identityHeaders
        - to
        - time
        - from
      properties:
        identityHeader:
          type: string
          description: This parameter contains the "shaken" Identity header field value to be verified
        identityHeaders:
          type: array
          items:
            type: string
          description: This array contains the "div" and "rph" Identity header field values to be verified
        to: 
          type: string
          description: The destination identity taken from the To header field. Used when no div claim is included
        dest: 
          type: string
          description: The destination identity taken from the Request-URI in the incoming request
        time: 
          type: integer
          description: Time based on the Date header field in the incoming request
        from: 
          type: string
          description: The asserted identity, taken from the P-Asserted-Identity or the From header field of the incoming request
        protectedHeaders: 
          type: array
          items:
            type: string
          description: Contains the SIP header field(s) protected by claims in the PASSporT(s) of the identityHeaders array
